const actionTypes = {
    SET_AREA: 'SET_AREA',
    SET_AREA_SUGGESTIONS: 'SET_AREA_SUGGESTIONS',
    SET_SELECTED_SORT_BY: 'SET_SELECTED_SORT_BY',
    SET_FURNISHED_VALUE: 'SET_FURNISHED_VALUE',
    SET_MIN_BEDROOMS: 'SET_MIN_BEDROOMS',
    SET_PROPERTIES: 'SET_PROPERTIES',
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_MINIMUM_PRICE: 'SET_MINIMUM_PRICE',
    SET_MAXIMUM_PRICE: 'SET_MAXIMUM_PRICE',
    SET_FILTERS_VISIBLE: 'SET_FILTERS_VISIBLE',
    SET_LISTINGS_VISIBLE: 'SET_LISTINGS_VISIBLE'
}
export default actionTypes;